### ISSUE TITLE
Downloading multiple dlc's with one command

### ISSUE THREAD

**Issue by ghost** [AlexanderProd/zippyshare-downloader#2]
Hi,

when trying to download multiple dlc's at once. But I get an error:

```
UNKNOWN_VALUE: Unknown value: 3ecdd42926e1b43d9ea5d63425bb547b5e080701.dlc
    at commandLineArgs (/usr/local/lib/node_modules/zippyshare-downloader/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/zippyshare-downloader/src/index.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  value: 'example.dlc'
```

Could you fix that please?

Thanks.

Regards

**Comment by AlexanderProd** [comment]
As of now you can only download one dlc at a time.

**Comment by ghost** [comment]
OK
